[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
common = { path = "../common" }
dns-lookup = "2.0.4"
lazy_static = "1.5.0"
owo-colors = "4.2.0"
tokio = { version = "1.44.1", features = [ "full" ] }
